name: build & push image

on: 
  push:
    branches: [ main ]

env:
  REGISTRY: quay.io 
  IMAGE_NAME: periodic-table-visualization

jobs: 
  build-img:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Log in to Red Hat Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: registry.redhat.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


    - name: build
      id: build-image
      run: podman build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

    - name: Push to image registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}/sweng
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }} 
